version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    network_mode: host

  # Optional services - uncomment if needed
  # redis:
  #   image: redis:7-alpine
  #   command: redis-server --requirepass RedisPassword123!
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=am_user_management
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
#   redis_data: